language: node_js

node_js:
        - "7"
notifications:
  slack: cse112-sp19-team8:Z18CJp98p6trZ5YZOZZeatxM

sudo: required

addons:
  chrome: stable # have Travis install Chrome stable.

cache:
  directories:
    - Components/node_modules

script:
        - cd Components/
        - npm install
        - npm test
