npm install --save-dev testcafe-browser-provider-saucelabslanguage: node_js

node_js: "stable"

notifications:
  slack: cse112-sp19-team8:Z18CJp98p6trZ5YZOZZeatxM

dist: trusty
sudo: required

addons:
  chrome: stable # have Travis install Chrome stable.
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

cache:
  directories:
    - Components/node_modules

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
  - cd Components/
  - npm install
  - npm test
