#!/bin/sh
#
# Color for output.
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

cd Components
karma start --single-run --browsers ChromeHeadless karma.conf.js
if [ "$?" -ne "0" ]
then
  echo "${RED}ABORTING COMMIT. Unit tests failed.${NC}"
  exit 1
fi
standard --fix
if [ "$?" -ne "0" ]
then
  echo "${RED}ABORTING COMMIT. Style check failed. Fix Standard errors.${NC}"
  exit 1
fi

echo "${GREEN}Unit and Style Checking Passed.${NC}"
exit 0

